export let productList = [
    {
        id:1,
        name:'phone',
        price:100,
        quantity:15

    },
    {
        id:2,
        name:'telephone',
        price:200,
        quantity:15
    },
    {
        id:3,
        name:'cellphone',
        price:300,
        quantity:15
    },
    {
        id:4,
        name:'bird massenger',
        price:400,
        quantity:15
    },
    {
        id:5,
        name:'SMS',
        price:500,
        quantity:15
    },
    {
        id:6,
        name:'TPS',
        price:600,
        quantity:15
    },
    {
        id:7,
        name:'SMU',
        price:700,
        quantity:15
    },
    {
        id:8,
        name:'TPS',
        price:800,
        quantity:15
    },
  ]